MODEL:
  TYPE: fastpredNF_CIF_separate_cond_clusterGMM
  ENCODER_TYPE: trajectron

DATA:
  DATASET_NAME: "eth"
  TP:
    PRED_STATE: 'state_v'
    ACCEPT_NAN: True
  BATCH_SIZE: 1024
  NORMALIZED: False

SOLVER:
  USE_SCHEDULER: True
  WEIGHT_DECAY: 0.0
  LR: 5e-3
  SAVE_EVERY: 1

MGF:
  ENABLE: True
  CLUSTER_N: 7
  VAR_INIT: 0.7
  VAR_LEARNABLE: True
  POST_CLUSTER: 500